root = "."

[build]
  bin = "bin/main"
  cmd = "make migrate; make build"
  exclude_dir = ["postgres-data", "assets/dist", "bin", "backups", "cmd/migrate/"]
  exclude_regex = ["_templ\\.go"]
  exclude_unchanged = true
  include_ext = ["go", "templ", "html"]

[misc]
clean_on_exit = true


