[build]
cmd = "go build -o bin/main cmd/app/main.go"
bin = "bin/main"
exclude_dir = ["postgres-data", "assets/dist", "cmd/migrate", "backups", "migrations"]
include_ext = ["go", "templ", "html"]
exclude_unchanged = true
rerun = true

[misc]
clean_on_exit = true
