services:
  web:
    container_name: budgeting-web
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:7331"
    environment:
      - GOOSE_DBSTRING="user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} host=${DB_HOST} sslmode=disable"
      - GOOSE_DRIVER=postgres
      - GOOSE_MIGRATION_DIR=cmd/migrate/migrations
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: budgeting-db
    env_file: .env
    image: "postgres:latest"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
