services:
  app:
    container_name: budgeting-app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:7331"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - GOOSE_DBSTRING=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - GOOSE_DRIVER=postgres
      - GOOSE_MIGRATION_DIR=cmd/migrate/migrations
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: budgeting-db
    env_file: .env
    image: "postgres:latest"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
