version: "3.9"

services:
  web:
    env_file: .env
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "${WEB_OUTER_PORT}:${WEB_INNER_PORT}"
    environment:
      - VITE_API_URL=http://localhost:${API_OUTER_PORT}

  api:
    env_file: .env
    build:
      context: api
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${API_INNER_PORT}
    ports:
      - "${API_OUTER_PORT}:${API_INNER_PORT}"
    volumes:
      - ./api:/api

  db:
    env_file: .env
    image: "postgres:latest"
    ports:
      - "${DB_OUTER_PORT}:${DB_INNER_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
