version: "3.9"

services:
  web:
    env_file: .env
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-8000}:5173"
    environment:
      - VITE_API_URL=http://localhost:${API_PORT:-8001}

  api:
    env_file: .env
    build:
      context: api
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    ports:
      - "${API_PORT:-8001}:8080"
    volumes:
      - ./api:/api

  db:
    env_file: .env
    image: "postgres:latest"
    ports:
      - "${DB_PORT:-8002}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
