version: "3.9"

services:
  db:
    env_file: .env
    image: "postgres:latest"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migrations/20240127152423_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
