[tools]
"aqua:air-verse/air" = "latest"
"aqua:a-h/templ" = "latest"
"aqua:pressly/goose" = "latest"
"aqua:tailwindlabs/tailwindcss" = "3.4.17"
golangci-lint = "latest"
sqlc = "latest"

[env]
_.file = ".env"
DATABASE_URL = "postgresql://{{env.DB_USER}}:{{env.DB_PASSWORD}}@{{env.DB_HOST}}:{{env.DB_PORT}}/{{env.DB_NAME}}"
GOOSE_MIGRATION_DIR = "cmd/migrate/migrations"

[tasks.compile]
depends = ["sql", "templ", "tailwind"]
sources = ["**/*.go"]
outputs = ["bin/budgeting"]
env.CGO_ENABLED = 0
env.GOOS = "linux"
env.GOARCH = "arm64"
run = "go build -tags production -trimpath -ldflags='-s -w' -o bin/budgeting ./cmd/app"

[tasks.sql]
sources = ["cmd/migrate/migrations/*.sql"]
run = "sqlc generate"

[tasks.templ]
sources = ["components/**/*.templ"]
run = "templ generate"

[tasks.tailwind]
sources = ["assets/main.css"]
run = "tailwindcss -i ./assets/main.css -o ./assets/dist/tailwind.css --minify"

[tasks.db]
run = "docker compose up -d --wait db"

[tasks.db-down]
run = "docker compose stop db"

[tasks.server]
run = "air -c .air-server.toml"

[tasks.proxy]
run = "templ generate --watch --proxy=\"http://localhost:${APP_PORT}\" --open-browser=false -v --proxybind=0.0.0.0"

[tasks.tailwind-watch]
run = "air -c .air-tailwind.toml"

[tasks.sqlc-watch]
run = "air -c .air-sqlc.toml"

[tasks.dev]
depends = ["db"]
run = "mise run server ::: proxy ::: tailwind-watch ::: sqlc-watch"

[tasks.migrate]
run = "go run ./cmd/migrate up"

[tasks.migrate-create]
run = "goose create {{arg(name='name')}} sql"

[tasks.migrate-rollback]
run = "go run ./cmd/migrate down"

[tasks.lint]
run = "golangci-lint run"
