#!/usr/bin/env sh

process_line() {
  line=$1
  printf "$(date '+%Y-%m-%d %H:%M:%S') - %s - %s\n" "$SUPERVISOR_PROCESS_NAME" "$line"
}

exec 2> >(
  while read -r line; do
    process_line "$line"
  done
)

exec 1> >(
  while read -r line; do
    process_line "$line"
  done
)


exec "$@"
