name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  package:
    name: Debian package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Mise
        uses: jdx/mise-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.27.0'

      - name: Build Debian package
        run: |
          mise run deb
          mv bin/budgeting_0.1.0_arm64.deb bin/budgeting_arm64.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: budgeting-arm64
          path: bin/budgeting_arm64.deb
          retention-days: 30
