name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: gofmt, templ, sqlc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Mise
        uses: jdx/mise-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Run gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Run templ fmt
        run: templ fmt -fail .

      - name: Run sqlc diff
        run: sqlc diff .
